/run/verbose 1
/run/initialize 
#/control/verbose 2
#/tracking/verbose 0
/tracking/storeTrajectory 2

# cambia el material del detector (BF3Gas, He3Gas)
/shield/sample/setSampleDetMat	--

# cambia el radio del detector
/shield/sample/Diametro_Det	--

#Cambia largo del detector
/shield/sample/sampleThickness	--

# cambia el material del Aluminio (Aluminium)
/shield/sample/setSampleMatAl	--

# cambia el radio de lamina de ALuminio
/shield/sample/Diametro_Al	--

# cambia el material de la lamina de (Aluminium,Air)
/shield/sample/setSampleMatCad	--

# cambia el radio de lamina de Cadmio
/shield/sample/Diametro_Cad	--

# cambia el material moderador del Core (Polyethylene_TS, Boron_Polyethylene_TS,Air)
/shield/sample/setSampleMatCore	--

#Cambia el Espesor del Core  en X
/shield/sample/sampleThicknessX_Core	--

#Cambia el Espesor del Core  en Y
/shield/sample/sampleThicknessY_Core	--

#Cambia el Espesor del Core  en Z
/shield/sample/sampleThicknessZ_Core	--

# cambia el material moderador de la Primera Capa (Polyethylene_TS, Boron_Polyethylene_TS,Cadmium,Air,Vacuum)
/shield/sample/setSampleMatC1	--


#Cambia el Espesor del material moderador 1 en X
/shield/sample/sampleThicknessX	--

#Cambia el Espesor del material moderador 1 en Y
/shield/sample/sampleThicknessY	--

#Cambia el Espesor del material moderador 1 en Z
/shield/sample/sampleThicknessZ	--

# cambia el material moderador de la Segunda Capa (Polyethylene_TS, Boron_Polyethylene_TS,Cadmium,Air,Vacuum)
/shield/sample/setSampleMatC2	--

#Cambia el Espesor del material moderador 2 en X
/shield/sample/sampleThicknessX_2	--

#Cambia el Espesor del material moderador 2 en Y
/shield/sample/sampleThicknessY_2	--

#Cambia el Espesor del material moderador 2 en Z
/shield/sample/sampleThicknessZ_2	--


# cambia el material moderador de la Tercera Capa (Polyethylene_TS, Boron_Polyethylene_TS,Cadmium,Air,Vacuum)
/shield/sample/setSampleMatC3	--

#Cambia el Espesor del material moderador 3 en X
/shield/sample/sampleThicknessX_3	--

#Cambia el Espesor del material moderador 3 en Y
/shield/sample/sampleThicknessY_3	--

#Cambia el Espesor del material moderador 3 en Z
/shield/sample/sampleThicknessZ_3	--


/gps/particle neutron
/gps/pos/centre 110 0 0 cm
/gps/ang/type iso  #Dirección isotrópica
/gps/ang/mintheta 79 deg
/gps/ang/maxtheta 101 deg
/gps/ang/minphi 354 deg
/gps/ang/maxphi 366 deg

# energy distribution

/gps/ene/type User
/gps/hist/type energy
/gps/ene/diffspec 1 


/gps/hist/point 0	0
/gps/hist/point	0	0
/gps/hist/point	1e-12	1

/run/beamOn 100000
