/run/verbose 1
/run/initialize 
#/control/verbose 2
#/tracking/verbose 0
/tracking/storeTrajectory 2

/gps/verbose 0

/vis/modeling/trajectories/create/drawByParticleID 
/vis/modeling/trajectories/drawByParticleID-0/set neutron red
/vis/modeling/trajectories/drawByParticleID-0/set gamma white


/gps/particle neutron
/gps/pos/centre 60 0 0 cm

#/gps/ang/type iso


#/gps/ang/type beam1d 
/gps/direction -1 0 0
/gps/energy 1 eV
#numero de particulas  
/run/beamOn 50
